version: 1.8.2
destination: _site
source: .
exclude: [
  grunt,
  node_modules, test, README.md,
  Gemfile, Gemfile.lock, rakefile,
  Web-toolkit.iml, circle.yml, Gruntfile.js,package.json]
include: [_includes, lib]
port: 4000
