version: 0.7.4
destination: _site
source: .
exclude: [grunt, node_modules, test, Gemfile, Gemfile.lock,rakefile,README.md,Web-toolkit.iml,circle.yml,Gruntfile.js,package.json]
include: [_includes]
port: 4000
