version: 2.0.0
destination: _site
source: .
exclude: [
  grunt,
  node_modules, test, README.md,
  Gemfile, Gemfile.lock, rakefile,
  Web-toolkit.iml,web-toolkit.ipr, web-toolkit.iws,circle.yml, Gruntfile.js,package.json,
  build.txt,
  deprecated, lib]
include: [_includes, test]
port: 4000
